version: "3.9"

services:
  web-chat-app:
    container_name: web-chat-app
    build: ./src
    working_dir: /usr/app/src
    command: sh -c "
      alembic upgrade head && python main.py
      "
    environment:
      - ENVIRONMENT=container
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - web-chat-db

  web-chat-db:
    image: postgres:latest
    container_name: web-chat-db
    command: -p 5532
    environment:
      - POSTGRES_USER=web-chat-db
      - POSTGRES_PASSWORD=web-chat-db
      - POSTGRES_DB=web-chat-db
    ports:
      - "5532:5532"