version: "3.9"

services:
  web-chat-app:
    container_name: web-chat-app
    build: ./src
    working_dir: /usr/app/src
    command: sh -c "
      alembic upgrade head && python main.py
      "
    environment:
      - ENVIRONMENT=container
    ports:
      - "8000:8000"
    depends_on:
      web-chat-db:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8000/chat
      interval: 60s
      timeout: 3s
      retries: 3

  web-chat-db:
    image: postgres:latest
    container_name: web-chat-db
    command: -p 5532
    environment:
      - POSTGRES_USER=web-chat-db
      - POSTGRES_PASSWORD=web-chat-db
      - POSTGRES_DB=web-chat-db
    expose:
      - 5532
    ports:
      - "5532:5532"
    volumes:
      - pvr-db-data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -p 5532 -U web-chat-db -d web-chat-db
      interval: 60s
      timeout: 3s
      retries: 3

volumes:
  pvr-db-data: