version: "3.9"

services:
  app:
    container_name: web-chat-app
    build: ./src
    working_dir: /usr/app/src
    command: sh -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
    environment:
      - ENVIRONMENT=container
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nCj4Fipk
      - POSTGRES_DB=web-chat
    ports:
      - "5432:5432"
