"""Added the updated_at and created_at fields to the tables

Revision ID: dc75e0b41d09
Revises: 6ba64933ce6d
Create Date: 2024-12-02 10:00:56.073902

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dc75e0b41d09"
down_revision = "6ba64933ce6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("messages", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("messages_id_idx"), "messages", ["id"], unique=False)
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("users_id_idx"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("users_id_idx"), table_name="users")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_index(op.f("messages_id_idx"), table_name="messages")
    op.drop_column("messages", "updated_at")
    op.drop_column("messages", "created_at")
    # ### end Alembic commands ###
