"""added message table

Revision ID: 6ba64933ce6d
Revises: 30e6f5b85aa7
Create Date: 2024-11-21 09:33:30.189193

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ba64933ce6d"
down_revision = "30e6f5b85aa7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], name=op.f("messages_sender_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    # ### end Alembic commands ###
